export type NamedColor = { name: string; emoji: string; hex: number };

// The first 25 entries are shown by default (Discord's autocomplete limit).
// They cover the full spectrum so users see a rainbow before typing anything.
// All remaining entries are reachable by typing part of the color name.
export const NAMED_COLORS: NamedColor[] = [
  // ─── DEFAULT RAINBOW (shown before the user types anything) ───
  { name: "Red", emoji: "🔴", hex: 0xff0000 },
  { name: "Coral", emoji: "🪸", hex: 0xff6b6b },
  { name: "Orange", emoji: "🟠", hex: 0xff8c00 },
  { name: "Amber", emoji: "🟡", hex: 0xffbf00 },
  { name: "Yellow", emoji: "🟡", hex: 0xffd700 },
  { name: "Lime", emoji: "💚", hex: 0x32cd32 },
  { name: "Green", emoji: "🟢", hex: 0x00c800 },
  { name: "Emerald", emoji: "💚", hex: 0x50c878 },
  { name: "Mint", emoji: "🌿", hex: 0x98ff98 },
  { name: "Teal", emoji: "🩵", hex: 0x008080 },
  { name: "Cyan", emoji: "🩵", hex: 0x00ffff },
  { name: "Sky Blue", emoji: "🌤️", hex: 0x87ceeb },
  { name: "Cornflower", emoji: "💙", hex: 0x6495ed },
  { name: "Royal Blue", emoji: "👑", hex: 0x4169e1 },
  { name: "Navy", emoji: "🔵", hex: 0x000080 },
  { name: "Indigo", emoji: "💜", hex: 0x4b0082 },
  { name: "Violet", emoji: "🟣", hex: 0x8a2be2 },
  { name: "Purple", emoji: "🟣", hex: 0x800080 },
  { name: "Lavender", emoji: "💜", hex: 0xb57bee },
  { name: "Magenta", emoji: "🌸", hex: 0xff00ff },
  { name: "Hot Pink", emoji: "💗", hex: 0xff1493 },
  { name: "Pink", emoji: "🩷", hex: 0xff69b4 },
  { name: "Rose", emoji: "🌹", hex: 0xff007f },
  { name: "White", emoji: "⬜", hex: 0xffffff },
  { name: "Discord Blurple", emoji: "💬", hex: 0x5865f2 },

  // ─── REDS ───
  { name: "Crimson", emoji: "🔴", hex: 0xdc143c },
  { name: "Scarlet", emoji: "🔴", hex: 0xff2400 },
  { name: "Ruby", emoji: "🔴", hex: 0x9b111e },
  { name: "Carmine", emoji: "🔴", hex: 0x960018 },
  { name: "Vermillion", emoji: "🔴", hex: 0xe34234 },
  { name: "Candy Apple Red", emoji: "🍎", hex: 0xff0800 },
  { name: "Raspberry", emoji: "🍇", hex: 0xe30b5d },
  { name: "Maroon", emoji: "🔴", hex: 0x800000 },
  { name: "Burgundy", emoji: "🍷", hex: 0x800020 },
  { name: "Wine", emoji: "🍷", hex: 0x722f37 },
  { name: "Oxblood", emoji: "🔴", hex: 0x4a0000 },
  { name: "Cherry", emoji: "🍒", hex: 0xde3163 },
  { name: "Brick Red", emoji: "🧱", hex: 0xcb4154 },
  { name: "Fire Engine Red", emoji: "🚒", hex: 0xce2029 },
  { name: "Tomato", emoji: "🍅", hex: 0xff6347 },
  { name: "Lava", emoji: "🌋", hex: 0xcf1020 },
  { name: "Blood Red", emoji: "🩸", hex: 0x8a0303 },
  { name: "Redwood", emoji: "🌲", hex: 0xa45a52 },
  { name: "Lollipop Red", emoji: "🍭", hex: 0xff3855 },

  // ─── PINKS ───
  { name: "Deep Pink", emoji: "🩷", hex: 0xff1493 },
  { name: "Light Pink", emoji: "🩷", hex: 0xffb6c1 },
  { name: "Baby Pink", emoji: "🩷", hex: 0xf4c2c2 },
  { name: "Pastel Pink", emoji: "🩷", hex: 0xffd1dc },
  { name: "Blush", emoji: "🌸", hex: 0xde5d83 },
  { name: "Bubblegum", emoji: "🍬", hex: 0xff85cf },
  { name: "Flamingo", emoji: "🦩", hex: 0xfc8eac },
  { name: "Carnation", emoji: "🌸", hex: 0xff6f8e },
  { name: "Fuchsia", emoji: "💖", hex: 0xff77ff },
  { name: "Hot Magenta", emoji: "💖", hex: 0xff0090 },
  { name: "Orchid Pink", emoji: "🌺", hex: 0xf2a7bb },
  { name: "Cherry Blossom", emoji: "🌸", hex: 0xffb7c5 },
  { name: "Amaranth", emoji: "🌹", hex: 0xe52b50 },
  { name: "Watermelon", emoji: "🍉", hex: 0xfc6c85 },
  { name: "Melon", emoji: "🍈", hex: 0xfdbcb4 },
  { name: "Cotton Candy", emoji: "🍭", hex: 0xffbcd9 },
  { name: "Neon Pink", emoji: "🩷", hex: 0xff6ec7 },
  { name: "Sunset Pink", emoji: "🌅", hex: 0xfda4af },

  // ─── ORANGES ───
  { name: "Deep Orange", emoji: "🟠", hex: 0xff5722 },
  { name: "Tangerine", emoji: "🍊", hex: 0xf28500 },
  { name: "Pumpkin", emoji: "🎃", hex: 0xff7518 },
  { name: "Burnt Orange", emoji: "🟠", hex: 0xcc5500 },
  { name: "Tiger Orange", emoji: "🐯", hex: 0xfd7f20 },
  { name: "Dark Amber", emoji: "🟡", hex: 0xff7e00 },
  { name: "Rust", emoji: "🟠", hex: 0xb7410e },
  { name: "Burnt Sienna", emoji: "🎨", hex: 0xe97451 },
  { name: "Sienna", emoji: "🟤", hex: 0xa0522d },
  { name: "Terra Cotta", emoji: "🏺", hex: 0xe2725b },
  { name: "Copper", emoji: "🟤", hex: 0xb87333 },
  { name: "Cinnamon", emoji: "🫙", hex: 0xd2691e },
  { name: "Apricot", emoji: "🍑", hex: 0xfbceb1 },
  { name: "Peach", emoji: "🍑", hex: 0xffcba4 },
  { name: "Salmon", emoji: "🐟", hex: 0xfa8072 },
  { name: "Hot Orange", emoji: "🔥", hex: 0xff4500 },
  { name: "Sunset Orange", emoji: "🌅", hex: 0xfd5e53 },
  { name: "Neon Orange", emoji: "🟠", hex: 0xff6700 },

  // ─── YELLOWS ───
  { name: "Bright Yellow", emoji: "🟡", hex: 0xffff00 },
  { name: "Lemon", emoji: "🍋", hex: 0xfff44f },
  { name: "Banana", emoji: "🍌", hex: 0xfce883 },
  { name: "Canary", emoji: "🐤", hex: 0xffff99 },
  { name: "Sunshine", emoji: "☀️", hex: 0xffda03 },
  { name: "Mustard", emoji: "🌭", hex: 0xffdb58 },
  { name: "Dark Mustard", emoji: "🟡", hex: 0xd4a017 },
  { name: "Saffron", emoji: "🌼", hex: 0xf4c430 },
  { name: "Gold", emoji: "🥇", hex: 0xffd700 },
  { name: "Dark Gold", emoji: "🏅", hex: 0xb8860b },
  { name: "Goldenrod", emoji: "🌻", hex: 0xdaa520 },
  { name: "Vanilla", emoji: "🍦", hex: 0xf3e5ab },
  { name: "Cream", emoji: "🤍", hex: 0xfffdd0 },
  { name: "Champagne", emoji: "🍾", hex: 0xf7e7ce },
  { name: "Neon Yellow", emoji: "🟡", hex: 0xccff00 },
  { name: "Laser Lemon", emoji: "🔆", hex: 0xffff66 },
  { name: "Starlight", emoji: "✨", hex: 0xf0e68c },

  // ─── GREENS ───
  { name: "Lime Green", emoji: "💚", hex: 0x9acd32 },
  { name: "Bright Green", emoji: "🟢", hex: 0x66ff00 },
  { name: "Neon Green", emoji: "🟢", hex: 0x39ff14 },
  { name: "Electric Green", emoji: "⚡", hex: 0x00ff00 },
  { name: "Dark Emerald", emoji: "💚", hex: 0x046307 },
  { name: "Forest Green", emoji: "🌲", hex: 0x228b22 },
  { name: "Dark Green", emoji: "🌲", hex: 0x006400 },
  { name: "Hunter Green", emoji: "🌿", hex: 0x355e3b },
  { name: "Jungle Green", emoji: "🌴", hex: 0x29ab87 },
  { name: "Bottle Green", emoji: "🍶", hex: 0x006a4e },
  { name: "Mint Green", emoji: "🌿", hex: 0x8fff8f },
  { name: "Seafoam", emoji: "🌊", hex: 0x71eeb8 },
  { name: "Spring Green", emoji: "🌱", hex: 0x00ff7f },
  { name: "Sage", emoji: "🌱", hex: 0x8fbc8f },
  { name: "Fern", emoji: "🌿", hex: 0x4f7942 },
  { name: "Moss", emoji: "🪨", hex: 0x8a9a5b },
  { name: "Olive", emoji: "🫒", hex: 0x808000 },
  { name: "Dark Olive", emoji: "🫒", hex: 0x556b2f },
  { name: "Jade", emoji: "💎", hex: 0x00a86b },
  { name: "Malachite", emoji: "💎", hex: 0x0bda51 },
  { name: "Avocado", emoji: "🥑", hex: 0x568203 },
  { name: "Pistachio", emoji: "🌰", hex: 0x93c572 },
  { name: "Celadon", emoji: "🍵", hex: 0xace1af },
  { name: "Radioactive", emoji: "☢️", hex: 0x65fe08 },
  { name: "Aurora Green", emoji: "🌌", hex: 0x00ff87 },
  { name: "Seafoam Green", emoji: "🌊", hex: 0x2eb8a4 },

  // ─── TEALS & CYANS ───
  { name: "Dark Teal", emoji: "🩵", hex: 0x003f3f },
  { name: "Light Teal", emoji: "🩵", hex: 0x30d5c8 },
  { name: "Aqua", emoji: "💧", hex: 0x00ffef },
  { name: "Aquamarine", emoji: "💎", hex: 0x7fffd4 },
  { name: "Turquoise", emoji: "🩵", hex: 0x40e0d0 },
  { name: "Dark Turquoise", emoji: "🩵", hex: 0x00ced1 },
  { name: "Cerulean", emoji: "🌀", hex: 0x007ba7 },
  { name: "Peacock Blue", emoji: "🦚", hex: 0x005f6b },
  { name: "Cadet Blue", emoji: "🩵", hex: 0x5f9ea0 },
  { name: "Powder Blue", emoji: "🩵", hex: 0xb0e0e6 },
  { name: "Robin Egg Blue", emoji: "🐦", hex: 0x00cccc },
  { name: "Tropical Blue", emoji: "🏝️", hex: 0x00b4d8 },
  { name: "Moonstone", emoji: "🌙", hex: 0x3aa8c1 },

  // ─── BLUES ───
  { name: "Blue", emoji: "🔵", hex: 0x0000ff },
  { name: "Bright Blue", emoji: "🔵", hex: 0x0080ff },
  { name: "Light Blue", emoji: "🩵", hex: 0xadd8e6 },
  { name: "Baby Blue", emoji: "🩵", hex: 0x89cff0 },
  { name: "Pastel Blue", emoji: "🩵", hex: 0xaec6cf },
  { name: "Cobalt", emoji: "🔵", hex: 0x0047ab },
  { name: "Sapphire", emoji: "💎", hex: 0x0f52ba },
  { name: "Dark Sapphire", emoji: "💎", hex: 0x082567 },
  { name: "Midnight Blue", emoji: "🌃", hex: 0x191970 },
  { name: "Prussian Blue", emoji: "🔵", hex: 0x003153 },
  { name: "Periwinkle", emoji: "🫐", hex: 0xccccff },
  { name: "Ice Blue", emoji: "🧊", hex: 0x99c5c4 },
  { name: "Denim", emoji: "👖", hex: 0x1560bd },
  { name: "Steel Blue", emoji: "⚙️", hex: 0x4682b4 },
  { name: "Slate Blue", emoji: "🩵", hex: 0x6a5acd },
  { name: "Neon Blue", emoji: "⚡", hex: 0x4d4dff },
  { name: "Electric Blue", emoji: "⚡", hex: 0x7df9ff },
  { name: "Ocean Blue", emoji: "🌊", hex: 0x006994 },
  { name: "Deep Sea Blue", emoji: "🌊", hex: 0x003366 },
  { name: "Iris", emoji: "🌸", hex: 0x5a4fcf },
  { name: "Azure", emoji: "🔵", hex: 0x007fff },
  { name: "Lapis", emoji: "💎", hex: 0x26619c },
  { name: "Bubblegum Blue", emoji: "🫧", hex: 0x54c8e8 },
  { name: "Nebula Blue", emoji: "🌌", hex: 0x4e5d94 },

  // ─── PURPLES ───
  { name: "Bright Purple", emoji: "🟣", hex: 0x9400d3 },
  { name: "Light Purple", emoji: "💜", hex: 0xbf80ff },
  { name: "Blue Violet", emoji: "🟣", hex: 0x8a2be2 },
  { name: "Dark Indigo", emoji: "💜", hex: 0x310062 },
  { name: "Lavender Blue", emoji: "💜", hex: 0x8c82fc },
  { name: "Wisteria", emoji: "🌺", hex: 0xc9a0dc },
  { name: "Plum", emoji: "💜", hex: 0xdda0dd },
  { name: "Dark Plum", emoji: "💜", hex: 0x580f41 },
  { name: "Amethyst", emoji: "💎", hex: 0x9966cc },
  { name: "Dark Amethyst", emoji: "💎", hex: 0x6d3b8e },
  { name: "Grape", emoji: "🍇", hex: 0x6f2da8 },
  { name: "Eggplant", emoji: "🍆", hex: 0x614051 },
  { name: "Mauve", emoji: "💜", hex: 0xe0b0ff },
  { name: "Orchid", emoji: "🌸", hex: 0xda70d6 },
  { name: "Thistle", emoji: "🌿", hex: 0xd8bfd8 },
  { name: "Heliotrope", emoji: "🌸", hex: 0xdf73ff },
  { name: "Tyrian Purple", emoji: "👑", hex: 0x66023c },
  { name: "Electric Purple", emoji: "⚡", hex: 0xbf00ff },
  { name: "Neon Purple", emoji: "⚡", hex: 0xbc13fe },
  { name: "Ultra Violet", emoji: "🟣", hex: 0x5f4b8b },
  { name: "Byzantium", emoji: "🟣", hex: 0x702963 },
  { name: "Mulberry", emoji: "🫐", hex: 0xc54b8c },
  { name: "Lilac", emoji: "💜", hex: 0xc8a2c8 },
  { name: "Galaxy Purple", emoji: "🌌", hex: 0x663399 },
  { name: "Aurora Purple", emoji: "🌌", hex: 0xbf5fff },
  { name: "Candy Grape", emoji: "🍬", hex: 0xa15cbe },
  { name: "Dusk Purple", emoji: "🌆", hex: 0x7b5ea7 },

  // ─── BROWNS ───
  { name: "Brown", emoji: "🟤", hex: 0x8b4513 },
  { name: "Dark Brown", emoji: "🟤", hex: 0x5c3317 },
  { name: "Light Brown", emoji: "🟤", hex: 0xb5651d },
  { name: "Chocolate", emoji: "🍫", hex: 0x7b3f00 },
  { name: "Mocha", emoji: "☕", hex: 0x967969 },
  { name: "Coffee", emoji: "☕", hex: 0x6f4e37 },
  { name: "Caramel", emoji: "🍮", hex: 0xc68642 },
  { name: "Tan", emoji: "🟤", hex: 0xd2b48c },
  { name: "Sand", emoji: "🏖️", hex: 0xc2b280 },
  { name: "Khaki", emoji: "👖", hex: 0xc3b091 },
  { name: "Taupe", emoji: "🟤", hex: 0x483c32 },
  { name: "Sepia", emoji: "📷", hex: 0x704214 },
  { name: "Beige", emoji: "🟤", hex: 0xf5f5dc },

  // ─── GRAYS & BLACKS ───
  { name: "Silver", emoji: "🪙", hex: 0xc0c0c0 },
  { name: "Light Gray", emoji: "🩶", hex: 0xd3d3d3 },
  { name: "Gray", emoji: "🩶", hex: 0x808080 },
  { name: "Dark Gray", emoji: "🩶", hex: 0xa9a9a9 },
  { name: "Slate", emoji: "🪨", hex: 0x708090 },
  { name: "Ash", emoji: "🌫️", hex: 0xb2beb5 },
  { name: "Charcoal", emoji: "⬛", hex: 0x36454f },
  { name: "Gunmetal", emoji: "🔫", hex: 0x2a3439 },
  { name: "Jet Black", emoji: "⬛", hex: 0x0a0a0a },
  { name: "Onyx", emoji: "⬛", hex: 0x353839 },
  { name: "Platinum", emoji: "🔘", hex: 0xe5e4e2 },

  // ─── METALLICS ───
  { name: "Rose Gold", emoji: "💖", hex: 0xb76e79 },
  { name: "Antique Gold", emoji: "🪙", hex: 0xd4af37 },
  { name: "Brass", emoji: "🎺", hex: 0xb5a642 },
  { name: "Bronze", emoji: "🥉", hex: 0xcd7f32 },
  { name: "Pewter", emoji: "🪙", hex: 0x96a8a1 },
  { name: "Steel", emoji: "⚙️", hex: 0x71797e },

  // ─── DISCORD & SPECIALS ───
  { name: "Discord Green", emoji: "💬", hex: 0x57f287 },
  { name: "Discord Yellow", emoji: "💬", hex: 0xfee75c },
  { name: "Discord Red", emoji: "💬", hex: 0xed4245 },
  { name: "Toxic Green", emoji: "☠️", hex: 0x75ff33 },
  { name: "Slime Green", emoji: "🟢", hex: 0x84de02 },
];
